### ISSUE TITLE
Icon disappears for a split of a second in FlipLoader when using svg

### ISSUE THREAD

**Issue by neo-xy** [samarthagarwal/FlutterScreens#31]
Hi,
I modifed code for Fliploader so that it takes a SvgPicture instead of IconData - but with that a bugg came up:
afeter every rotation, svg image disappears for a split second, 
does any one maybe know why?And is there anything that can be done to fix that?

best regards!

**Comment by samarthagarwal** [comment]
It could be because of the way the SVG images are being loaded. Since they are files, it is possible that they are read from the storage every time and hence take a little bit to show up. You may have to tweak the code a little bit to implement some sort of caching. I do not have a concrete solution but this is what I would try to rule out first.
